/* 계정 ?��?�� �? 권한 �??�� */
CREATE USER eutcha
IDENTIFIED BY 1234;

GRANT CONNECT, RESOURCE, DBA TO eutcha;

/* ?��?���? ?��?�� */
DROP TABLE member;
DROP TABLE leave_member;
DROP TABLE movie_info;
DROP TABLE movie_ranking;
DROP TABLE staffs_info;
DROP TABLE keyword_info;
DROP TABLE star_rating;
DROP TABLE eutcha_comment;
DROP TABLE comment_like;
DROP TABLE comment_report;
DROP TABLE faq;
DROP TABLE qna;
DROP TABLE notice;
DROP TABLE wanna_watch;
DROP TABLE PICK;
DROP TABLE movie_pick;

/* ?��???�� ?��?�� */
DROP SEQUENCE seq_leave_member_index;
DROP SEQUENCE notice_seq;
DROP SEQUENCE qna_seq;
DROP SEQUENCE faq_seq;
DROP SEQUENCE seq_wanna_watch_index;
DROP SEQUENCE seq_movie_ranking_index;
DROP SEQUENCE movie_info_seq;
DROP SEQUENCE staffs_info_seq;
DROP SEQUENCE keyword_info_seq;
DROP SEQUENCE seq_star_rating;
DROP SEQUENCE seq_eutcha_comment;
DROP SEQUENCE seq_comment_like;
DROP SEQUENCE seq_comment_report;
DROP SEQUENCE PICK_SEQ;
DROP SEQUENCE movie_pick_seq;

/* ?��?�� ?��?���? */
CREATE TABLE MEMBER (
    member_email VARCHAR2(128) PRIMARY KEY,
    member_nickname VARCHAR2(45) UNIQUE NOT NULL,
    member_pwd VARCHAR2(512) NOT NULL,
    member_pwd_salt VARCHAR2(512) NOT NULL,
    member_date DATE DEFAULT SYSDATE,
    admin_check VARCHAR2(20) DEFAULT 'N' NOT NULL ,
    member_status VARCHAR2(20)DEFAULT 'N' NOT NULL ,
    member_photo VARCHAR2(256) NULL,
    member_introduce VARCHAR2(1000) NULL,
    member_join_route VARCHAR2(50)DEFAULT 'O' NOT NULL 
);

/* ?��?��?��?�� ?��?���? */
CREATE TABLE LEAVE_MEMBER (
    leave_member_index NUMBER PRIMARY KEY,
    fk_member_email VARCHAR2(128) NOT NULL,
    reason1 NUMBER DEFAULT 0 NOT NULL,
    reason2 NUMBER DEFAULT 0 NOT NULL,
    reason3 NUMBER DEFAULT 0 NOT NULL,
    reason4 NUMBER DEFAULT 0 NOT NULL,
    leave_date DATE DEFAULT SYSDATE  NOT NULL,
    FOREIGN KEY(fk_member_email) REFERENCES member(member_email) on delete cascade
);

/* ?��?��?��?�� ?��???�� */
CREATE SEQUENCE seq_leave_member_index
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999
NOCYCLE; 

/* ?��?��?���? ?��?���? */
CREATE TABLE MOVIE_INFO (
	MOVIE_DOCID	VARCHAR2(100) PRIMARY KEY,
    TITLE VARCHAR2(200)  NULL,
	TITLE_ORG	VARCHAR2(200) NULL,
	NATION	VARCHAR2(100) NULL,
	MOVIE_RUNNING_TIME	VARCHAR2(100) NULL,
	RATING	VARCHAR2(100) NULL,
	PRODYEAR	VARCHAR2(100) NULL,
	POSTER_URI	VARCHAR2(1000) NULL,
	GENRE	VARCHAR2(100) NULL,
	PLOT	VARCHAR2(4000) NULL
);

/*?��?��?��?��보테?���?*/
CREATE TABLE STAFFS_INFO (
	staff_INDEX	NUMBER	NOT NULL,
	FK_MOVIE_DOCID	VARCHAR2(100)	NOT NULL,
	STAFF_NAME	VARCHAR2(256)	NOT NULL,
    STAFF_ROLE_GROUP VARCHAR2(100) NOT NULL,
    STAFF_ROLE VARCHAR2(100) NULL
);

/*?��?��?��?��?��조건*/
ALTER TABLE STAFFS_INFO
ADD CONSTRAINT FK_STAFFS_INFO FOREIGN KEY(FK_MOVIE_DOCID) REFERENCES MOVIE_INFO(MOVIE_DOCID)
ON DELETE CASCADE;

/*?��?��?��?��보테?���?*/
CREATE TABLE KEYWORD_INFO (
	KEYWORD_INDEX	NUMBER	NOT NULL,
	FK_MOVIE_DOCID	VARCHAR2(100)	NOT NULL,
	KEYWORD_INFO	VARCHAR2(100)	NULL
);

/*?��?��?�� ?��?��조건*/
ALTER TABLE KEYWORD_INFO
ADD CONSTRAINT FK_KEYWORD_INFO FOREIGN KEY(FK_MOVIE_DOCID) REFERENCES MOVIE_INFO(MOVIE_DOCID)
ON DELETE CASCADE;

/*?��???��모음*/
CREATE SEQUENCE MOVIE_INFO_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE SEQUENCE STAFFS_INFO_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE SEQUENCE KEYWORD_INFO_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE;

/* ?��?��?���? ?��?�� ?��?�� */
CREATE TABLE MOVIE_RANKING(
    MOVIE_RANKING_INDEX NUMBER PRIMARY KEY,
    FK_MOVIE_DOCID VARCHAR2(100) NOT NULL,
    MOVIE_RANKING NUMBER NOT NULL,
    MOVIE_PLATFORM CHAR(2) DEFAULT 'W' NOT NULL,
    FOREIGN KEY(FK_MOVIE_DOCID) REFERENCES MOVIE_INFO(MOVIE_DOCID) ON DELETE CASCADE
);
    
/* MOVIE_RANKING_INDEX ?��???�� */
CREATE SEQUENCE SEQ_MOVIE_RANKING_INDEX
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999
NOCYCLE; 

/* 보고?��?��?�� */
CREATE TABLE WANNA_WATCH (
    wanna_watch_index NUMBER NOT NULL, --seq
    fk_member_email VARCHAR2(128)   NOT NULL,
    fk_movie_docid  VARCHAR2(100)   NOT NULL,
    wanna_watch_date DATE DEFAULT SYSDATE NOT NULL,
    FOREIGN KEY(fk_movie_docid) REFERENCES MOVIE_INFO (MOVIE_DOCID) on delete cascade,
    FOREIGN KEY(fk_member_email) REFERENCES MEMBER (MEMBER_EMAIL) on delete cascade
);

/* 보고?��?��?�� ?��???�� */
CREATE SEQUENCE SEQ_WANNA_WATCH_INDEX
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999
NOCYCLE;

/* 별점 ?��?���? */
CREATE TABLE star_rating(
    star_index NUMBER PRIMARY KEY,
    fk_movie_docid VARCHAR2(100) NOT NULL,
    fk_member_email VARCHAR2(128) NOT NULL,
    star_rating NUMBER NOT NULL
);

/* 별점 ?��???�� */
CREATE SEQUENCE seq_star_rating 
START WITH 1 
INCREMENT BY 1 
MAXVALUE 999999
NOCYCLE;

/* 별점 FK ?��?��조건 */
ALTER TABLE star_rating 
ADD CONSTRAINT fk_member_star_rating
FOREIGN KEY (fk_member_email) REFERENCES member (member_email) ON DELETE CASCADE ;

ALTER TABLE star_rating 
ADD CONSTRAINT fk_movie_docid_star_rating
FOREIGN KEY (fk_movie_docid) REFERENCES movie_info (movie_docid) ON DELETE CASCADE ;

/* 코멘?�� ?��?���? */
CREATE TABLE eutcha_comment(
    comment_index NUMBER PRIMARY KEY,
    fk_star_index NUMBER NOT NULL,
    comment_text VARCHAR2(2000) NOT NULL,
    comment_like_count NUMBER DEFAULT 0 NOT NULL,
    comment_report_count NUMBER DEFAULT 0 NOT NULL,
    comment_blind_check NUMBER DEFAULT 0 NOT NULL,
    comment_date DATE DEFAULT SYSDATE NOT NULL
);

/* 코멘?�� ?��???�� */
CREATE SEQUENCE seq_eutcha_comment
START WITH 1 
INCREMENT BY 1 
MAXVALUE 999999
NOCYCLE;

/* 코멘?�� FK ?��?��조건 */
ALTER TABLE eutcha_comment 
ADD CONSTRAINT fk_star_index_comment
FOREIGN KEY (fk_star_index) REFERENCES star_rating (star_index) ON DELETE CASCADE ;

/* 좋아?�� ?��?���? */
CREATE TABLE comment_like(
    like_index NUMBER PRIMARY KEY,
    fk_comment_index NUMBER NOT NULL,
    fk_member_email VARCHAR2(128) NOT NULL,
    like_check NUMBER DEFAULT 0 NOT NULL
);

/* comment_like ?��???�� */
CREATE SEQUENCE seq_comment_like
START WITH 1 
INCREMENT BY 1 
MAXVALUE 999999
NOCYCLE;

/* 좋아?�� FK ?��?��조건 */
ALTER TABLE comment_like 
ADD CONSTRAINT fk_member_comment_like
FOREIGN KEY (fk_member_email) REFERENCES member (member_email) ON DELETE CASCADE ;

ALTER TABLE comment_like 
ADD CONSTRAINT fk_comment_index_comment_like
FOREIGN KEY (fk_comment_index) REFERENCES eutcha_comment (comment_index) ON DELETE CASCADE ;

/* ?��고하�? ?��?���? */
CREATE TABLE comment_report(
    report_index NUMBER PRIMARY KEY,
    fk_comment_index NUMBER NOT NULL,
    fk_member_email VARCHAR2(128) NOT NULL,
    report_text VARCHAR2(2000) NOT NULL
);

/* comment_report ?��???�� */
CREATE SEQUENCE seq_comment_report
START WITH 1 
INCREMENT BY 1 
MAXVALUE 999999
NOCYCLE;

/* comment_report FK ?��?��조건 */
ALTER TABLE comment_report 
ADD CONSTRAINT fk_member_comment_report
FOREIGN KEY (fk_member_email) REFERENCES member (member_email) ON DELETE CASCADE ;

ALTER TABLE comment_report 
ADD CONSTRAINT fk_comment_index_report
FOREIGN KEY (fk_comment_index) REFERENCES eutcha_comment (comment_index) ON DELETE CASCADE ;

/* 공�??��?�� */
CREATE TABLE NOTICE (
    NOTICE_NO NUMBER PRIMARY KEY,
    member_email VARCHAR2(128) NOT NULL,
    NOTICE_TITLE VARCHAR2(45) NOT NULL,
    NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
    NOTICE_DATE DATE DEFAULT SYSDATE,
    NOTICE_FILES NVARCHAR2(1000) NULL,
    NOTICE_PUB NUMBER NOT NULL
);

/* ?��주묻?��질문 */
CREATE TABLE FAQ (
    FAQ_NO NUMBER PRIMARY KEY,
    member_email VARCHAR2(128) NOT NULL,
    FAQ_TITLE VARCHAR2(45) NOT NULL,
    FAQ_CONTENT VARCHAR2(4000)  NOT NULL,
    FAQ_PUB NUMBER NOT NULL
);

/* ?��???��문의 */
CREATE TABLE QNA (
    QNA_NO NUMBER PRIMARY KEY,
    member_email VARCHAR2(128) NOT NULL,
    QNA_TITLE VARCHAR2(45) NOT NULL,
    QNA_CONTENT VARCHAR2(4000) NOT NULL,
    QNA_DATE DATE DEFAULT SYSDATE,
    QNA_FILES NVARCHAR2(1000) NULL,
    QNA_ANSWER NUMBER DEFAULT 0,
    ANSWER_CONTENT VARCHAR2(4000) NULL,
    ANSWER_FILES NVARCHAR2(1000) NULL
);

/* NOTICE_SEQ ?��???�� ?��?�� */
CREATE SEQUENCE NOTICE_SEQ
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

/* QNA_SEQ ?��???�� ?��?�� */
CREATE SEQUENCE QNA_SEQ
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

/* FAQ_SEQ ?��???�� ?��?�� */
CREATE SEQUENCE FAQ_SEQ
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;
    
/*NOTICE ?��?��?�� ?��?��조건*/
ALTER TABLE NOTICE ADD CONSTRAINT FK_MEMBER_TO_NOTICE
FOREIGN KEY (MEMBER_EMAIL)REFERENCES MEMBER (MEMBER_EMAIL) ON DELETE CASCADE ;

/*FAQ ?��?��?�� ?��?��조건*/
ALTER TABLE FAQ ADD CONSTRAINT FK_MEMBER_TO_FAQ 
FOREIGN KEY (MEMBER_EMAIL)REFERENCES MEMBER (MEMBER_EMAIL) ON DELETE CASCADE ;

/*QNA ?��?��?�� ?��?��조건*/
ALTER TABLE QNA ADD CONSTRAINT FK_MEMBER_TO_QNA FOREIGN KEY 
(MEMBER_EMAIL)REFERENCES MEMBER (MEMBER_EMAIL) ON DELETE CASCADE ;


/* ?��?��?�� ?��?���? */
CREATE TABLE PICK(
PICK_INDEX NUMBER PRIMARY KEY,
FK_MEMBER_EMAIL VARCHAR2(128),
PICK_NAME VARCHAR2(100)
);

CREATE TABLE MOVIE_PICK (
	PICKMOVIE_INDEX	NUMBER	 PRIMARY KEY,
	FK_PICK_INDEX NUMBER,
    FK_MOVIE_DOCID VARCHAR2(50)
);

/* ?��?��?�� FK?��?��조건 */
ALTER TABLE PICK
ADD CONSTRAINT FK_PICK FOREIGN KEY(FK_MEMBER_EMAIL) REFERENCES MEMBER(MEMBER_EMAIL)
ON DELETE CASCADE;

ALTER TABLE MOVIE_PICK
ADD CONSTRAINT FK_PICK_INDEX FOREIGN KEY(FK_PICK_INDEX) REFERENCES PICK(PICK_INDEX)
ON DELETE CASCADE;

ALTER TABLE MOVIE_PICK
ADD CONSTRAINT FK_MOVIE_PICK_DOCID FOREIGN KEY(fk_movie_docid) REFERENCES MOVIE_INFO(MOVIE_DOCID)
ON DELETE CASCADE;

/* ?��?��?�� ?��???�� */
CREATE SEQUENCE PICK_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE;

CREATE SEQUENCE MOVIE_PICK_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE;


/* movie_info add column */
ALTER TABLE movie_info ADD(movie_trailer varchar2(1000));
ALTER TABLE movie_info ADD(movie_hit_count NUMBER DEFAULT 0 NOT NULL);

/* staff_info add column*/
ALTER TABLE staffs_info ADD(staff_id VARCHAR2(1000));

/* 20210222 LMY - add major_genre table */

CREATE TABLE MAJOR_GENRE (
FK_MOVIE_DOCID VARCHAR(100),
MAJOR_GENRE VARCHAR (256));

ALTER TABLE MAJOR_GENRE
ADD CONSTRAINT FK_MOVIE_DOCID FOREIGN KEY(FK_MOVIE_DOCID) REFERENCES MOVIE_INFO(MOVIE_DOCID)
ON DELETE CASCADE;

ALTER TABLE MAJOR_GENRE
MODIFY MAJOR_GENRE NOT NULL;